mashmatrix/react-lightning-design-system

- package.json
- src/scripts/Picklist.js
This PR gives to the ability to:
1. Set a value in the picklist even if it's not in the picklist items yet. (I am fetching the options from the server only when the list opens).
2. Set the value to 'any'. Ids in SF are strings, so we should be able to accept both strings and integers.
> Set for remote

- src/scripts/Icon.js
- test/icon-spec.js
When Icon's category is specified in `<Icon icon="<category>:<icon>" />` notation, category is not reflected and does not yield expected result.
> Fix icon category is not reflected in "<category>:<icon>" notation

- src/scripts/DropdownButton.js
If the component is getting unmounted at this point, no DOM node will be found and .trigger will fail.
> Fix Dropdown Button issue when unmounting

- src/scripts/Modal.js
ModalContent was throwing a validation error when multiple children were added to it.  Corrected to "Proptypes.node" to fix incorrect validation.
> Correct prop validation: ModalContent

- examples/public/index.html
- src/scripts/Tabs.js
In IE11 tab menu is hidden. Fix stylesheet `overflow` property.
> Fix tabmenu rendering in IE11

- examples/client/scripts/components/FormExamples.js
- src/scripts/Checkbox.js
- src/scripts/CheckboxGroup.js
- src/scripts/DateInput.js
- src/scripts/FormElement.js
- src/scripts/Input.js
- src/scripts/Picklist.js
- src/scripts/RadioGroup.js
- src/scripts/Select.js
- src/scripts/Textarea.js
In this PR it adds support of required indicator (*) in form element fields by `required` property.
It also adds error message in `error` property when it has any errors (e.g. validation failure).
This is coming from #29, but differs bacause it is not including any validation logic inside.
Component users should care about it and add any validation or error detection logic outside of the components.
> Add support of error message and required indicator in form elements

- src/scripts/FormElement.js
- src/scripts/Lookup.js
This fixes a warning when passing an actual error (e.g string) to FormElement, and enables `required` and `error` props in Lookup element.
> Fixed proptypes in FormElement and required indication in Lookup

- src/scripts/Datepicker.js
Way to reproduce bug:
1. Update location:
moment.updateLocale ('pl');
2. Display calendar.
This problem concerns days of the week on the top bar of the calendar that did not agree with the actual dates (for example, 14.06 is described as Monday in pol lang).
Fix also improves displaying correctly 'first day of week’ (Monday for non-USA).
> improvement order of days in week for other locales

- examples/client/scripts/components/FormExamples.js
- src/scripts/DateInput.js
By adding `includeTime` prop in DateInput, enable passing datetime value and editing time inside of text input field.
> Accept time value and edit time in dateinput

- README.md
As the repository has moved to mashmatrix org, there is a need to rewrite URLs from personal one to organization.
> Change URLs in Readme

- src/scripts/DateInput.js
When initial value is not set to DateInput, the rendered dropdown doesn't have default focus, and cannot move to target month/year in datepicker control.
> Fix date input cannot switch month/year in dropdown picker

- .eslintrc
- examples/.eslintrc
- package.json
- test/.eslintrc
To prevent the filename case error in CI (which might not be easily notified in local MacOS environment), include lint check for unresolved files importing
> Fix eslint to include unresolved module check

- src/scripts/Lookup.js
The lookup search icon comes to left when no `iconAlign` prop is specified - which was not the default previously. Reset to right by default.
> Fix lookup icon align default to right

- package.json
Fix the version of dependent lint libs in order to prevent errors when the dependent eslint libs are updated.
> Fix version of lint libs to prevent auto-update errors

- src/scripts/Lookup.js
As the `onSelect` property handler to lookup component is passed down to lookup search component and its `input` html element, the select event handler will be fired unexpectedly.
Exclude unused props when passing down to child component.
Fixes #131 .
> Fix onSelect will be called when the lookup search has selected

- src/scripts/DateInput.js
The previous commits bring corruption in dateformat handling in DateInput component.
- Should accept raw ISO8601-based date/datetime format in value/defaultValue.
- Should emit raw ISO8601-based date/datetime format in `onValueChange`.
- The `dateFormat` prop default should not be set in defaultProps because it will change when `includeTime` prop is set. Use `getInputValueFormat()`.
Fixes #114.
> Revert the dateinput format handlings

- examples/package.json
- examples/webpack.config.js
fix for `npm run start:dev` command in `examples` folder
> fix react-hot-loader for webpack dev server

- src/scripts/DateInput.js
- src/scripts/Datepicker.js
Due to the calendar icon of DateInput which has no tabIndex right now, clicking calendar icon will fire the onBlur and onComplete event because it loses the cursor focus from the component. This is also for datepicker container element.
Add proper tabIndex attribute to these element to judge the blur event correctly.
> Fix DateInput onBlur/onComplete event is fired when the focus is still inside of the component

- src/scripts/Picklist.js
As the message and translation is developers' concern, should be empty by default.
Closes #146
> Set default value to empty text for selectedText/optionsSelectedText props

- src/scripts/FormElement.js
In horizontal form, the dropdown menu is rendered with a wide space between input control and menu.
> Fix style of dropdown menu in horizontal form

- src/scripts/DropdownMenu.js
As the transform-runtime cannot cover the instance methods conversion,
these prototype methods will require the library users to load polyfills implicityly.
Fixes #168
> Remove es6 array.prototype methods

- src/scripts/Icon.js
[LDS Medium Size](https://lightningdesignsystem.com/components/icons/#flavor-sizes-medium) is a valid icon size and the default size for icons. This PR allows the user to also explicitly specify `medium` as a size prop.
> Allow 'medium' to be a valid Icon size

- .storybook/__storyshots__/Form.shot
- .storybook/__storyshots__/Lookup.shot
- .storybook/__storyshots__/Modal.shot
- src/scripts/Lookup.js
- stories/LookupStories.js
Support meta information in lookup entry. If no meta in entry it will only shows its label.
> Support meta information displaying in lookup candidates

- .storybook/__storyshots__/Form.shot
- .storybook/__storyshots__/Lookup.shot
- .storybook/__storyshots__/Modal.shot
- src/scripts/Lookup.js
IE11 has problem rendering slds-media in lookup candidate. Change to use direct styling of inline-flex in display.
> Fix lookup candidate rendering in ie11

- src/scripts/AutoAlign.js
As the SLDS in VF assumes elements to locate under the `slds-scope` DOM element, a portal (dropdown) element - which locates under the document.body - should be marked with class name of `slds-scope`.
The `<CustomSettings>` component can set this, but the default class name should be `slds-scope` without adding custom setting.
Close #273
> Add default portal class to work without adding setting

- src/scripts/DateInput.js
- src/scripts/Lookup.js
- test/storyshots/__snapshots__/storyshots.test.js.snap
In firefox the control icon in dateinput/lookup cannot gain focus when clicked, and results blur event to fire.
Similar issues:
https://stackoverflow.com/questions/28772810/in-firefox-click-on-absolute-element-inside-focusable-element-does-not-focus-fo
Above shows adding `position: relative` style solves this issue, and it did work.
> Prevent blur event when clicked calendar/search icon in dateinput/lookup component in Firefox

- package.json
- stories/LookupStories.js
- test/setupTests.js
- yarn.lock
> [WIP]Update React to v16

- .eslintrc.js
- src/scripts/AutoAlign.js
- src/scripts/Button.js
- src/scripts/Datepicker.js
- src/scripts/DropdownButton.js
- src/scripts/Lookup.js
- src/scripts/Table.js
- stories/IconStories.js
- stories/ModalStories.js
- test/breadcrumbs-spec.js
- test/storyshots/__snapshots__/storyshots.test.js.snap
> Configure ESLint

- src/scripts/DateInput.js
- src/scripts/Lookup.js
- test/storyshots/__snapshots__/storyshots.test.js.snap
This reverts PR #278 .
Because the problem occurred in the PR seems fixed in current Firefox (v70.0 mac),
and that change now causes the broken layout issue in Chrome (I confirmed with Mac Chrome 78.0.3904.70).
> Revert "#278 fix-blur-in-icon-click"

- src/scripts/DropdownMenu.tsx
As re-creating children is not preferable and type safe.
> Use context instead of copying menuSelect handler to props

- src/scripts/AutoAlign.tsx
The configs like `assetRoot` is not propagated to elements in portalized popup
> fix to propagate comp settings to comps in portal

- src/scripts/Tabs.tsx
- test/storyshots/__snapshots__/storyshots.test.js.snap
Add tabIndex to the tab menu (related to #387)
> Fix to moving out the focus when clicked tab menu in Safari/firefox

- package.json
- src/scripts/DropdownMenu.tsx
- stories/DropdownMenu.stories.tsx
The DropdownMenu component could not control the opening and closing of nested submenus, and when switching between submenus, the original menu remained open.
When a submenu is switched, the original menu should be closed and the newly clicked menu should be opened.
- Manage the opening and closing of all menus with objects
- Move state management to parent component and pass it to child components in context
> Enhance DropdownMenu Component to Control Nested Submenu Visibility

- package.json
- src/scripts/AutoAlign.tsx
- src/scripts/Popover.tsx
- src/scripts/Tabs.tsx
- stories/Tabs.stories.tsx
We want to be able to add an arbitrary tooltip to the `Tabs` component using `Popover`.
- ~~Add `tooltipText` and `tooltipContent` as prop.~~
- Add `tooltip` props (ReactNode) to the Tabs component.
- Tooltip cases added to `Tabs.stories`
- Allow `Popover` to use ref and hide Tooltip when out of focus.
> Add optional tooltip prop to Tabs component

- src/scripts/TreeNode.tsx
In scenarios where child tree nodes are fetched and displayed during field lookups, clicking the toggle caused the tree to collapse. 
This issue was due to the button becoming hidden and losing focus during loading. 
This fix ensures that the button remains visible and retains focus during the loading state, preventing the tree from closing unexpectedly.
- Kept the button visible during loading by setting its `opacity: 0`, ensuring it retains focus.
- Positioned the Spinner with `position: absolute` to overlay it on the button.
> Fix preserve button focus during loading state

- src/scripts/FormElement.tsx
- src/scripts/Tabs.tsx
- src/scripts/TooltipContent.tsx
This PR extracts the TooltipContent component to be an independent component and integrates it into both the Tabs and FormElement components. 
Additionally, it adds the tooltip option to the FormElement component.
- Added the tooltip option to the FormElement component.
- Extracted TooltipContent as an independent component.
- Integrated TooltipContent into the Tabs and FormElement component.
> Extract TooltipContent Component and Add to FormElement

- src/scripts/CheckboxGroup.tsx
- src/scripts/FormElement.tsx
- src/scripts/RadioGroup.tsx
Moved `required` mark's position from right to left, in order to follow the latest SLDS's way.
https://www.lightningdesignsystem.com/components/input/#Required
> Move `required` mark's position

- src/scripts/Checkbox.tsx
- src/scripts/CheckboxGroup.tsx
- src/scripts/DateInput.tsx
- src/scripts/Input.tsx
- src/scripts/Lookup.tsx
- src/scripts/Picklist.tsx
- src/scripts/RadioGroup.tsx
- src/scripts/Select.tsx
- src/scripts/Textarea.tsx
- stories/Checkbox.stories.tsx
- stories/DateInput.stories.tsx
- stories/Input.stories.tsx
- stories/Lookup.stories.tsx
- stories/Picklist.stories.tsx
- stories/Radio.stories.tsx
- stories/Select.stories.tsx
- stories/Textarea.stories.tsx
Closes #451 
- Add `tooltip` and `tooltipIcon` acceptance in components that use FormElement internally: 772046e7d9fde4e9d13484eb34af76769c602871
- `Input/Textarea/Select/Picklist/Lookup/DateInput/Checkbox`
- Add `TooltipContent` to `CheckboxGroup` and `RadioGroup` to accept it: 2066d28440eb8b2a9a3cd6d95d8e6431aa408c92
- Add stories with tooltip
> Changed to accept tooltips in components that use FormElement internally

- src/scripts/Badge.tsx
- stories/Badge.stories.tsx
- update a classname
- remove unsupported `type`s
- add newly supported `type`s
Whether we need to add new types (`lightest`, `success` `warning`, and `error`).
https://v1.lightningdesignsystem.com/components/badges/
> Update `Badge` for SLDS2

- src/scripts/Tree.tsx
- src/scripts/TreeNode.tsx
- update markups
- update classnames
- improve a11y
https://v1.lightningdesignsystem.com/components/trees/
> Update `Tree` and `TreeNode` for SLDS2

- src/scripts/PageHeader.tsx
- src/scripts/Text.tsx
- stories/PageHeader.stories.tsx
- restrict category only classname to `title`
- remove `label` from the `type` props, because it's no longer listed as a classname
Whether to update `PageHeaderDetailBody` without backward compatibility.
- https://v1.lightningdesignsystem.com/utilities/text/
- https://v1.lightningdesignsystem.com/utilities/text/#CSS-Class-Overview
> Update `Text` for SLDS2

- src/scripts/Select.tsx
- pass `id` as `controlId`
- insert `.slds-select_container` inside the `FormElement`
https://v1.lightningdesignsystem.com/components/select/
> Update `Select` for SLDS2

- src/scripts/Tabs.tsx
- src/scripts/Tree.tsx
Reflecting https://github.com/mashmatrix/react-lightning-design-system/pull/472#discussion_r2156145801 to components that were already merged (`Tree` and `Tabs`).
> Remove `aria-labelledby`s for SLDS2

- src/scripts/Lookup.tsx
- src/scripts/Picklist.tsx
- update markups to combobox pattern
- update classnames for dropdown sizing
- improve a11y for disabled state
https://v1.lightningdesignsystem.com/components/picklist/
> Update `Picklist` for SLDS2

- src/scripts/Icon.tsx
- src/scripts/Lookup.tsx
- src/scripts/Spinner.tsx
- stories/Icon.stories.tsx
- stories/Lookup.stories.tsx
- stories/Spinner.stories.tsx
- Lookup
- update markups significantly
- improve a11y
- Spinner
- add a `layout` prop
- add an `x-small` size
- Icon
- add an `xx-small` size
https://v1.lightningdesignsystem.com/components/lookups/
> Update `Lookup` for SLDS2

- src/scripts/Picklist.tsx
- restore the following props
- Picklist
- inputRef
- PicklistItem
- onClick
- icon
- iconRight
- divider
- normalize markups around `Icon`
> Restore props for SLDS2

- src/scripts/Picklist.tsx
- remove `slds-size_small`, which wouldn't be needed, from the portal classnames
> Adjust `Picklist`'s portal classnames for SLDS2

- src/scripts/Lookup.tsx
- src/scripts/Picklist.tsx
- convert tags of elements with `role="combobox"` to `<input type="text" readonly />`s
- extract text contents in `findSelectedItemLabel()` in `Picklist`
> Convert `combobox`es to `input`s for SLDS2

- src/scripts/Lookup.tsx
- switch the `has-icon_` classname based on whether the selected item has an icon
> Consider cases without icon for selected item in `Lookup` for SLDS2
