README.md, examples/bower.json, examples/package.json, examples/server/app.js
=> Remove bower dependency

examples/package.json, src/scripts/DropdownMenu.js, src/scripts/Tabs.js
=> Support SLDS 0.12.x

.babelrc, src/scripts/DropdownButton.js, src/scripts/DropdownMenu.js, src/scripts/Picklist.js
The stylesheet visibility control seems affecting to this. Change menu visibility to be controlled by react, not :focus stylesheet.
=> Dropdown button menu item click fails sometime

package.json
=> Babel-runtime is not included in npm install

.gitignore, .travis.yml, karma.conf.js, package.json, src/scripts/Icon.js, test/.eslintrc, test/button-spec.js
- Karma
- Mocha
- Sinon, Chai
- Istanbul
- react-addons-test-utils
=> Test structure

karma.conf.js, package.json, src/scripts/Badge.js, src/scripts/Button.js, test/.eslintrc, test/badge-spec.js, test/button-spec.js
- Add lib enzyme
- Covered tests for Button and ButtonIcon components
- Changed tests for Badge
- Added label attr for Badge
=> Button component tests

karma.conf.js
Set `babel-plugin-espower` plugin in babelify transform in browserify setting in karma.conf.
=> Update karma.conf to add power-assert capability

examples/client/scripts/components/TabsExamples.js, src/scripts/SalesPath.js, src/scripts/index.js
Let me know your thoughts.  
Will do the examples for form validation shortly but have deadlines.
=> Added SalesPath with Examples

src/scripts/Modal.js
Add support to Modal Header to support taglines.
=> Update Modal.js to support tagline.

examples/client/scripts/components/FormExamples.js, examples/client/scripts/components/TreeExamples.js, examples/package.json, src/scripts/Button.js, src/scripts/Checkbox.js, src/scripts/CheckboxGroup.js, src/scripts/DateInput.js, src/scripts/FieldSet.js, src/scripts/Form.js, src/scripts/FormElement.js, src/scripts/Input.js, src/scripts/Lookup.js, src/scripts/Picklist.js, src/scripts/RadioGroup.js, src/scripts/Select.js, src/scripts/Textarea.js, src/scripts/TreeNode.js, test/button-spec.js
Change to use SLDS version to 1.0, and keep up with the official latest version. 
#41 is the list which we need to check before merging to master.
=> Support SLDS ver 1.0

examples/client/scripts/components/LookupExamples.js, examples/client/scripts/components/ModalExamples.js, src/scripts/Button.js, src/scripts/Datepicker.js, src/scripts/DropdownMenu.js, src/scripts/FieldSet.js, src/scripts/Form.js, src/scripts/FormElement.js, src/scripts/Icon.js, test/button-spec.js
- Dropdown rendering of form element (picklist / dateinput)
- Dropdown button rendering
- Datepicker year pulldown
=> Fix form element rendering issues

examples/client/scripts/components/LookupExamples.js, examples/client/scripts/components/data/CAMPAIGNS.js, examples/client/scripts/components/data/CASES.js, examples/client/scripts/components/data/OPPORTUNITIES.js, examples/client/scripts/components/data/SCOPES.js, src/scripts/Button.js, src/scripts/DropdownButton.js, src/scripts/FormElement.js, src/scripts/Input.js, src/scripts/Lookup.js, test/button-spec.js
Enable lookup to include scope selection if `scopes` property is given.
See http://www.lightningdesignsystem.com/components/lookups/#multi-scope .
=> Add support of multi-scope lookup

.travis.yml
Add cache entry in .travis.yml setting.
=> Enable cache of node_modules in travis ci

examples/client/scripts/components/Root.js
To access easily to the source code of the example, set link to uppper right of each example pages.
=> Add link to each examples to view source code of the examples

src/scripts/Lookup.js
Fix to lookup from pull 68, cause @david-a probably forgot about it.
=> Fix lookup

.gitignore, examples/client/scripts/components/DatepickerExamples.js, examples/client/scripts/components/MediaObjectExamples.js, examples/client/scripts/components/PageHeaderExamples.js, examples/client/scripts/components/PopoverExamples.js, examples/client/scripts/components/Root.js, src/scripts/Button.js, src/scripts/ButtonGroup.js, src/scripts/Checkbox.js, src/scripts/DateInput.js, src/scripts/Datepicker.js, src/scripts/DropdownButton.js, src/scripts/DropdownMenu.js, src/scripts/FormElement.js, src/scripts/Grid.js, src/scripts/Icon.js, src/scripts/MediaObject.js, src/scripts/Modal.js, src/scripts/PageHeader.js, src/scripts/Popover.js, src/scripts/Spinner.js, src/scripts/index.js, src/scripts/util.js
Made some changes to components and add some new
main changes:
1) Change some components to handle styles prop
2) Change some components to make them more flexible
3) Fix two bugs that were causing js errors in some cases
4) Add new components
This code was smoke-tested by me on the examples, works fine.
All logic is separated by commits. @ButuzGOL @stomita please take a look. Thanks.
=> Components fixes

src/scripts/Form.js, test/form-spec.js
This resolves https://github.com/mashmatrix/react-lightning-design-system/issues/106
=> Fix rendering of null children in Form

examples/client/scripts/components/IconExamples.js, examples/client/scripts/components/PageHeaderExamples.js, examples/client/scripts/components/Root.js, examples/package.json, src/scripts/Datepicker.js, src/scripts/Icon.js, src/scripts/Lookup.js, src/scripts/PageHeader.js, src/scripts/Select.js, src/scripts/Spinner.js, src/scripts/Table.js, src/scripts/Tabs.js, src/scripts/TreeNode.js
=> Upgrade to slds2

src/scripts/DateInput.js, src/scripts/Datepicker.js, src/scripts/Table.js, src/scripts/Tabs.js
Fixes #110
Removed styling when menu alignment is not set to right.
=> Fix DateInput menu rendering position (for 1.0 branch)

examples/client/scripts/components/FormExamples.js, examples/client/scripts/components/Root.js, examples/client/scripts/components/SpinnerExamples.js, examples/client/scripts/components/ToggleExamples.js, package.json, src/scripts/DateInput.js, src/scripts/DropdownButton.js, src/scripts/FormElement.js, src/scripts/Input.js, src/scripts/Lookup.js, src/scripts/Pill.js, src/scripts/Toggle.js, src/scripts/TreeNode.js, src/scripts/index.js
Changes:
- DateInput fix menu align propType
- DropDownButton count position for menu if overflow and scroll
- FormElement remove pos absolute because lookup dropdown width 0
- New components Pill and Toggle
- Symbol pattern ability for Input
- Spinners examples
- Item render ability for TreeNode
=> Additional fixes and components

src/scripts/FieldSet.js, src/scripts/Form.js, src/scripts/FormElement.js, src/scripts/Input.js, src/scripts/Select.js, src/scripts/Textarea.js
Change the FormElement wrapping not in container components (Form / FieldSet.Row) but in the form element itself.
Fixes #130
=> Fix duplicated errors rendered in form element

examples/client/scripts/components/FormExamples.js, src/scripts/Picklist.js, test/picklist-spec.js
- added new option `multiSelect` that is deafults to false
- state.value type is changed to be an array
if it is `true`:
-- allow select multiple lines
-- not close popup when selecting single line
=> support of multi select for PickList

src/scripts/Picklist.js
=> Render raw seleted value when the matching option is not found

examples/client/scripts/components/DatepickerExamples.js, examples/client/scripts/components/FormExamples.js, src/scripts/DateInput.js, src/scripts/Datepicker.js
To embed controls like "Today" button in datepicker, allow passing extension renderer to Datepicker and DateInput.
=> Allow appending extension component at bottom of datepicker

examples/client/scripts/components/DropdownButtonExamples.js, package.json, src/scripts/DropdownMenu.js, src/scripts/Grid.js, src/scripts/PageHeader.js, src/scripts/Table.js, src/scripts/Tabs.js, src/scripts/Text.js, src/scripts/index.js
1. Dropdown (MenuHeader, divider prop)
2. Grid ability to add tag not just div
3. PageHeader changes based on slds 2.0 (Details)
4. Table truncate for header
5. Tabs add tabs__item only on menuItems
6. Text add section prop and some changes of category and type
=> Enhancements

src/scripts/DateInput.js
Wrap the calendar icon in DateInput with span in order to get focused in IE.
=> Fix blur event occuring in DateInput in IE

examples/client/scripts/components/CardExamples.js, examples/client/scripts/components/Root.js, src/scripts/Card.js, src/scripts/index.js
https://www.lightningdesignsystem.com/components/cards/#flavor-base
=> New Card component

stories/GridStories.js
Fix error in running story of grid
=> Fix grid component ref in grid stories

.storybook/config.js, .storybook/head.html, package.json, public/.gitignore, yarn.lock
It might be changed in future, but the example src is moved to storybook, it should show the storybook in the demo site.
=> Make storybook as example site

.storybook/__storyshots__/Badge.shot, src/scripts/Badge.js
=> pass props through to Badge

.storybook/__storyshots__/Button.shot, .storybook/__storyshots__/ButtonGroup.shot, .storybook/__storyshots__/DateInput.shot, .storybook/__storyshots__/Datepicker.shot, .storybook/__storyshots__/DropdownButton.shot, .storybook/__storyshots__/Form.shot, .storybook/__storyshots__/Input.shot, .storybook/__storyshots__/Lookup.shot, .storybook/__storyshots__/Modal.shot, .storybook/__storyshots__/Notification.shot, .storybook/__storyshots__/PageHeader.shot, .storybook/__storyshots__/Picklist.shot, .storybook/__storyshots__/Table.shot, .storybook/__storyshots__/Tabs.shot, .storybook/__storyshots__/Tree.shot, src/scripts/Icon.js
=> Set SvgIcon href without __dangerouslySetInnerHtm

src/scripts/Icon.js
=> Add prop sanitization in icon/category property of Icon component

src/scripts/DateInput.js
=> Overwrite the error style of select when rendered in datepicker

.storybook/__storyshots__/DropdownButton.shot, .storybook/__storyshots__/Form.shot, .storybook/__storyshots__/Modal.shot, .storybook/__storyshots__/Picklist.shot, src/scripts/DropdownMenu.js, src/scripts/Picklist.js, stories/PicklistStories.js
=> Fix menu blur when clicked disabled menu or scroll bar

.storybook/__storyshots__/Form.shot, .storybook/__storyshots__/Lookup.shot, .storybook/__storyshots__/Modal.shot, src/scripts/Lookup.js
=> Fix not to fire blur event when clicked search icon in lookup component

.storybook/__storyshots__/Button.shot, .storybook/__storyshots__/ButtonGroup.shot, .storybook/__storyshots__/Datepicker.shot, .storybook/__storyshots__/DropdownButton.shot, .storybook/__storyshots__/Lookup.shot, .storybook/__storyshots__/Modal.shot, .storybook/__storyshots__/Notification.shot, .storybook/__storyshots__/PageHeader.shot, .storybook/__storyshots__/Table.shot, .storybook/__storyshots__/Tabs.shot, .storybook/__storyshots__/Tree.shot, src/scripts/Button.js, test/button-spec.js
=> Change svg icon in button not to accept pointer events

.storybook/__storyshots__/DateInput.shot, src/scripts/DateInput.js
=> Disable calendar icon click handling when dateinput is disabled

.storybook/__storyshots__/Lookup.shot, src/scripts/Lookup.js, stories/LookupStories.js
=> Disable lookup icon click / scope menu click when lookup component is disabled

.storybook/__storyshots__/Lookup.shot, src/scripts/Lookup.js
Previous modification bring corruption regarding with targetScope
=> Fix lookup component's scope selection is not working

.storybook/__storyshots__/Datepicker.shot, src/scripts/Datepicker.js
=> Allow to select out of month date in calendar

.storybook/__storyshots__/Form.shot, .storybook/__storyshots__/Modal.shot, .storybook/__storyshots__/Picklist.shot, src/scripts/Picklist.js
=> Fix picklist to accept disabled property

package.json, src/scripts/DropdownButton.js, src/scripts/FormElement.js, src/scripts/Input.js, src/scripts/Lookup.js, src/scripts/Picklist.js, src/scripts/Tabs.js, test/storyshots/__snapshots__/storyshots.test.js.snap, yarn.lock
Render dropdown menus in document.body root (portal)
Closes #254
=> Change dropdown rendering to use portal

package.json, yarn.lock
Use forked realtive-portal in dependency to prevent initialization error and force trigger update for scroll
=> Fix react-relative-portal initialization error

src/scripts/DateInput.js, src/scripts/Datepicker.js, src/scripts/Lookup.js
Add delay to focus dropdown element to handle correctly
=> Fix focusing date and lookup first entry

src/scripts/Table.js, stories/GridStories.js, stories/PicklistStories.js, stories/TableStories.js, yarn.lock
Fix error/warning of direct PropTypes usage on React module and missing key attribute for some stories.
=> Fix warnings of PropTypes and keys

src/scripts/AutoAlign.js
Fix setState() error when rendering/hiding dropdown menus
=> Clear dom/component reference when unmonted

src/scripts/CheckboxGroup.js, src/scripts/DropdownButton.js, src/scripts/Lookup.js, src/scripts/Picklist.js
Fixes querySelector on undefined error
=> add element existence check before accessing dom

.storybook/config.js, .storybook/wrapContent.js, src/scripts/AutoAlign.js, src/scripts/ComponentSettings.js, src/scripts/Icon.js, src/scripts/index.js
As the `setAssetRoot` globally modifies value, open a way to modify settings only on subtrees of the component
=> Add ComponentSettings component to apply settings to component subtrees

src/scripts/AutoAlign.js, src/scripts/DropdownButton.js
Allow absolute alignment with screen boundary in narrow screen to prevent overflow the dropdown
=> Update auto alighning in narrow screen

src/scripts/AutoAlign.js, src/scripts/DateInput.js, src/scripts/DropdownButton.js, src/scripts/Lookup.js, src/scripts/Picklist.js
In order to apply styles overriding for portaled dropdown, pass className to portaled root element
=> Add classname to pass portaled root

src/scripts/AutoAlign.js
Picklist dropdown / Lookup search candidate list is positioned invalid place
=> Fix portal positioning in picklist/lookup

src/scripts/Icon.js
=> Unset pointer events for svg/use element

src/scripts/DateInput.tsx, src/scripts/Lookup.tsx, test/storyshots/__snapshots__/storyshots.test.js.snap
This is the same contents as #343
=> Revert "#278 fix-blur-in-icon-click" to 3.0

package.json
to tell the portal elements to be refreshed
=> Fix exporting updateScroll() method

src/scripts/util.ts
to tell the portal elements to be refreshed
=> Fix exporting updateScroll() method (cont.)

package.json, src/scripts/AutoAlign.tsx
In order to align from right position the portal root should have full width of body element
=> fix portal root to have full width

src/scripts/Button.tsx, src/scripts/Checkbox.tsx, src/scripts/CheckboxGroup.tsx, src/scripts/DateInput.tsx, src/scripts/Datepicker.tsx, src/scripts/DropdownButton.tsx, src/scripts/DropdownMenu.tsx, src/scripts/FieldSet.tsx, src/scripts/FormElement.tsx, src/scripts/Input.tsx, src/scripts/Lookup.tsx, src/scripts/Picklist.tsx, src/scripts/Radio.tsx, src/scripts/RadioGroup.tsx, src/scripts/Select.tsx, src/scripts/Textarea.tsx, src/scripts/Toggle.tsx, src/scripts/hooks.ts, stories/Input.stories.tsx, stories/Lookup.stories.tsx, stories/Select.stories.tsx, stories/Textarea.stories.tsx, stories/Toggle.stories.tsx
Add unified interface to form element components
- Refs to HTML elements
- `onValueChange` handlers
=> Unify interface of components

src/scripts/CheckboxGroup.tsx, src/scripts/ComponentSettings.tsx, src/scripts/DateInput.tsx, src/scripts/DropdownButton.tsx, src/scripts/DropdownMenu.tsx, src/scripts/Lookup.tsx, src/scripts/Notification.tsx, src/scripts/Picklist.tsx, src/scripts/RadioGroup.tsx, src/scripts/SalesPath.tsx, src/scripts/Tabs.tsx, src/scripts/typeUtils.ts
- onValueChange timing of DateInput
- make bivariant for callback handlers with union type value returned
=> Fix public handlers behavior of components

package.json, src/scripts/hooks.ts, src/scripts/util.ts, yarn.lock
use more compact lib to generate unique id in HTML id generation
=> change uuid lib to nanoid

package.json, src/scripts/DateInput.tsx, src/scripts/Datepicker.tsx, stories/Datepicker.stories.tsx, yarn.lock
As moment.js is deprecated, we move to day.js
=> Replace moment.js to day.js

package.json, src/scripts/DateInput.tsx, src/scripts/FormElement.tsx, src/scripts/Input.tsx, src/scripts/Lookup.tsx, src/scripts/Picklist.tsx, src/scripts/Select.tsx, src/scripts/Textarea.tsx, src/scripts/Toggle.tsx, src/scripts/hooks.ts, src/scripts/util.ts, yarn.lock
As it requires random id generation, which is not suitable for stable regression testing
=> Explicitly focus control element when label is clicked instead of using htmlFor

src/scripts/CheckboxGroup.tsx, src/scripts/FormElement.tsx, src/scripts/RadioGroup.tsx
Added static title attribute for `required` mark.
Related to #450.
https://www.lightningdesignsystem.com/components/input/#Required
=> Add title for `required` mark

src/scripts/Grid.tsx
- replace the value of the vertical align prop from `medium` to `middle`
https://v1.lightningdesignsystem.com/utilities/grid/#site-main-content
=> Update `Grid` for SLDS2

src/scripts/Pill.tsx, stories/Pill.stories.tsx
- restrict the container tag to `span`
- make an a tag render depending on the `disabled` prop
- add an icon container instead of the `slds-pill__icon` classname
- https://v1.lightningdesignsystem.com/components/pills/
- https://v1.lightningdesignsystem.com/components/pills/#About-Pills
=> Update `Pill` for SLDS2

src/scripts/MediaObject.tsx, stories/MediaObject.stories.tsx
- replace the `figureCenter` prop that is an undocumented feature with `centered` that is a documented one
https://v1.lightningdesignsystem.com/utilities/media-objects/
=> Update `MediaObject` for SLDS2

src/scripts/Popover.tsx, stories/Popover.stories.tsx
- update markups
- improve a11y
https://v1.lightningdesignsystem.com/components/popovers/
=> Update `Popover` for SLDS2

src/scripts/FieldSet.tsx, src/scripts/FormElement.tsx
- update classnames
- add `aria-hidden='true'` to the `abbr` element
- apply `errorId`
- change a markup for `readOnly`
- apply `id` and `htmlFor` straightforwardly
- https://v1.lightningdesignsystem.com/components/form-element/
- https://v1.lightningdesignsystem.com/components/form-element/#Compound
=> Update `FormElement` and `FieldSet` for SLDS2

src/scripts/DropdownButton.tsx, src/scripts/DropdownMenu.tsx
- update markups
- update classnames
- improve a11y
https://v1.lightningdesignsystem.com/components/menus/
=> Update `DropdownMenu` and `DropdownButton` for SLDS2

src/scripts/PageHeader.tsx, stories/PageHeader.stories.tsx
- update markups significantly
- rename duplicated classnames
- https://v1.lightningdesignsystem.com/components/page-headers/
- https://v1.lightningdesignsystem.com/components/page-headers/#Base
- https://v1.lightningdesignsystem.com/components/page-headers/#Record-Home
- https://v1.lightningdesignsystem.com/components/page-headers/#Related-List
=> Update `PageHeader` for SLDS2

src/scripts/Textarea.tsx, stories/Textarea.stories.tsx
- update markup for `readOnly`
- update a classname
- improve a11y
https://v1.lightningdesignsystem.com/components/textarea/
=> Update `Textarea` for SLDS2

src/scripts/Toggle.tsx
- pass `id` as `controlId`
- remove undocumented `aria-live` attribute
- handle `aria-describedby`
https://v1.lightningdesignsystem.com/components/checkbox-toggle/
=> Update `Toggle` for SLDS2

src/scripts/Button.tsx, src/scripts/Lookup.tsx, src/scripts/Notification.tsx, src/scripts/Picklist.tsx, src/scripts/Tabs.tsx
- fix the following issues found on connecting to an external app
- Button
- stop showing `icon` as `title` (5fd7aff8003ad60e80b78d183d847916020eb72d, 152092484cab268d43ebd27e0ad2d3e50d7413c4)
- Tabs
- add `alt` prop instead of `title` (aa76ab800781f6574d6e8627d89ef61d209b02d3)
- Notificaion
- apply `currentColor` (55a4b06c47de67c9ebe1565cbd53299074806050)
- Picklist
- introduce `AutoAlign` (6190e699069886e2668478e3aa9aabfd7a4286d4, a498becf192b0f7beb41b22d3ad70c200ee8f168, c2ef2c8bad339882db3dbb1170f3ce2868326f12, a14a2d66f9b011cc7f5a0c168839d26d61da3993)
- remove the number of selected values from the label (7182b283a8e817a3ed6010681c5903d7b735959e)
- escape all the selector string (93fc5c29b5b05adbe57cf52bea7c282ee3f21608)
- add `.react-slds-picklist` …
=> Fix issues with external app
